# -*- encoding: utf-8 -*-
=begin
=実績設定

=end

#==============================================================================
# ■ NWConst::Library
#==============================================================================
module NWConst::Library  
  # メダル獲得時の効果音
  SE_GAIN_MEDAL = RPG::SE.new("Powerup", 90, 140)
  
  # 使用しないメダルID
  NO_USE_MEDAL = [
  ]
  
  MEDAL_DATA = {
    # 例
#   メダルID => { ※メダルIDは1~9999に収めてください
#      :icon_id => アイコンID,
#      :title => "タイトル",
#      :description => "解説",
#      :priority => :表示優先順位,
#    },
    1 => {
      :icon_id => 193,
      :title => "ハンスさん救出",
      :description => "さらわれた村人を救出した",
      :priority => 1,
    },
    2 => {
      :icon_id => 193,
      :title => "女神イリアス降臨",
      :description => "祝福なき勇者として認められた",
      :priority => 2,
    },
    3 => {
      :icon_id => 191,
      :title => "魔王のしもべ",
      :description => "魔王アリスを仲間にした……いや、された",
      :priority => 3,
    },
    4 => {
      :icon_id => 191,
      :title => "女神のしもべ",
      :description => "女神イリアスを仲間にした……いや、された",
      :priority => 4,
    },
    5 => {
      :icon_id => 193,
      :title => "ついてきた幼馴染み",
      :description => "ソニアが強引についてきた……",
      :priority => 5,
    },
    6 => {
      :icon_id => 193,
      :title => "勇気の証",
      :description => "「勇気の証」を発見し、兵士に認められた",
      :priority => 6,
    },
    7 => {
      :icon_id => 193,
      :title => "商人救出",
      :description => "遭難した商人を無事に救出した",
      :priority => 7,
    },
    8 => {
      :icon_id => 193,
      :title => "盗賊団壊滅",
      :description => "魔物盗賊団を壊滅させ、少女達を更正させた",
      :priority => 8,
    },
    9 => {
      :icon_id => 193,
      :title => "フェニックスの尾密売事件解決",
      :description => "だまされていたフェニックス娘を保護した",
      :priority => 9,
    },
    10 => {
      :icon_id => 192,
      :title => "並行世界の旅人",
      :description => "並行世界をも旅する冒険者",
      :priority => 10,
    },
    11 => {
      :icon_id => 193,
      :title => "ハーピー達の救い主",
      :description => "ハーピー達を伝染病から解放した",
      :priority => 11,
    },
    12 => {
      :icon_id => 193,
      :title => "素性不明のメダル女王",
      :description => "初めてメダル女王に謁見した",
      :priority => 12,
    },
    13 => {
      :icon_id => 193,
      :title => "ナメクジ退治",
      :description => "ナメクジタワーでナメクジのボスを倒した",
      :priority => 13,
    },
    15 => {
      :icon_id => 192,
      :title => "父の背中を追って",
      :description => "いつか、その背中に並ぶように",
      :priority => 15,
    },
    16 => {
      :icon_id => 193,
      :title => "失踪したミカエラ",
      :description => "いったい、どこに行ってしまったのか……",
      :priority => 16,
    },
    17 => {
      :icon_id => 192,
      :title => "はじめてのセントラ大陸",
      :description => "セントラ大陸、初上陸",
      :priority => 17,
    },
    18 => {
      :icon_id => 193,
      :title => "ショタハーレム崩壊",
      :description => "洗脳されていたメイアを倒した",
      :priority => 18,
    },
    19 => {
      :icon_id => 193,
      :title => "四精霊を追って",
      :description => "正しい歴史を歩み、そして力を得るために",
      :priority => 19,
    },
    20 => {
      :icon_id => 192,
      :title => "勇者として……",
      :description => "ミカエラの遺志、その胸に刻んで",
      :priority => 20,
    },
    21 => {
      :icon_id => 193,
      :title => "機甲法王七号機",
      :description => "教会の機密を知ってしまった……",
      :priority => 21,
    },
    22 => {
      :icon_id => 193,
      :title => "ゾンビの店仕舞い",
      :description => "クロムをこらしめ、お化け屋敷騒動に幕",
      :priority => 22,
    },
    23 => {
      :icon_id => 192,
      :title => "風の精霊",
      :description => "シルフの力を手に入れた",
      :priority => 23,
    },
    24 => {
      :icon_id => 193,
      :title => "熱き正義の魂",
      :description => "いわゆる巻き込まれ型ヒーロー",
      :priority => 24,
    },
    25 => {
      :icon_id => 193,
      :title => "黒きアリスの逆襲",
      :description => "悪夢の茶会は終わらない",
      :priority => 25,
    },
    26 => {
      :icon_id => 193,
      :title => "おてんば王女の名誉回復",
      :description => "サバサを救った知られざる英雄",
      :priority => 26,
    },
    27 => {
      :icon_id => 193,
      :title => "偶像のカーテンコール",
      :description => "サキちゃん、キラッ☆",
      :priority => 27,
    },
    28 => {
      :icon_id => 193,
      :title => "魔女の晩餐",
      :description => "マギステア村の紛争を解決した",
      :priority => 28,
    },
    29 => {
      :icon_id => 192,
      :title => "土の精霊",
      :description => "ノームの力を手に入れた",
      :priority => 29,
    },
    30 => {
      :icon_id => 191,
      :title => "滅びし世界の希望を",
      :description => "ラ・クロワから受け継がれた希望を胸に",
      :priority => 30,
    },
    31 => {
      :icon_id => 193,
      :title => "おさかな海賊団デビュー",
      :description => "おさかな海賊団の一員として活動を始めた",
      :priority => 31,
    },
    32 => {
      :icon_id => 193,
      :title => "海軍の誇り",
      :description => "海軍の一員として活動を始めた",
      :priority => 32,
    },
    33 => {
      :icon_id => 193,
      :title => "女王杯の覇者",
      :description => "女王杯に優勝し、その名を轟かせた",
      :priority => 33,
    },
    34 => {
      :icon_id => 193,
      :title => "すきやきの黄昏",
      :description => "ミノタウロス失踪事件を解決した",
      :priority => 34,
    },
    35 => {
      :icon_id => 193,
      :title => "神社巡り",
      :description => "ヤマタイ村の騒動を解決した",
      :priority => 35,
    },
    36 => {
      :icon_id => 193,
      :title => "彼女は裁かれた",
      :description => "魔導顧問メフィストの裏の顔を暴いた",
      :priority => 36,
    },
    37 => {
      :icon_id => 192,
      :title => "誰がために鐘は鳴る",
      :description => "この世は素晴らしい。戦う価値がある",
      :priority => 37,
    },
    38 => {
      :icon_id => 193,
      :title => "誰がために鐘は鳴る",
      :description => "この世は素晴らしい。戦う価値がある",
      :priority => 39,
    },
    39 => {
      :icon_id => 193,
      :title => "虫と花とトリとネコ",
      :description => "プランセクト村の内戦を治めた",
      :priority => 38,
    },
    40 => {
      :icon_id => 192,
      :title => "水の精霊",
      :description => "ウンディーネの力を手に入れた",
      :priority => 40,
    },
    41 => {
      :icon_id => 193,
      :title => "作戦開始",
      :description => "心強い助っ人を迎え、いよいよ作戦が始まる",
      :priority => 41,
    },
    42 => {
      :icon_id => 193,
      :title => "ゴルド砦突破",
      :description => "まだ作戦は始まったばかりだ",
      :priority => 42,
    },
    43 => {
      :icon_id => 193,
      :title => "進軍の丘突破",
      :description => "いよいよグランゴルド城は目前だ",
      :priority => 43,
    },
    44 => {
      :icon_id => 192,
      :title => "勝利の宴",
      :description => "グランゴルドを解放し、大戦争を終わらせた",
      :priority => 44,
    },
    45 => {
      :icon_id => 193,
      :title => "蠅の王",
      :description => "幽霊船のベルゼバブを退治した",
      :priority => 45,
    },
    46 => {
      :icon_id => 193,
      :title => "北の海から",
      :description => "ポセイドネスに力を示しオーブを受け取った",
      :priority => 46,
    },
    47 => {
      :icon_id => 193,
      :title => "サキュバスの狂宴",
      :description => "サキュバスの村での争いを解決した",
      :priority => 47,
    },
    48 => {
      :icon_id => 193,
      :title => "ヤングユニゾン",
      :description => "エミリとカサンドラを元の姿に戻した",
      :priority => 48,
    },
    49 => {
      :icon_id => 193,
      :title => "魔法少女ぐらん☆べりあ",
      :description => "見なかった事にしてあげよう",
      :priority => 49,
    },
    50 => {
      :icon_id => 192,
      :title => "炎の精霊",
      :description => "サラマンダーの力を手に入れた",
      :priority => 50,
    },
    51 => {
      :icon_id => 193,
      :title => "伝説をその目に",
      :description => "五百年前の世界で英雄ハインリヒに会った",
      :priority => 51,
    },
    52 => {
      :icon_id => 193,
      :title => "四大国救援",
      :description => "各国に押し寄せる魔王軍の先兵を破った",
      :priority => 52,
    },
    53 => {
      :icon_id => 193,
      :title => "エルフと妖精の午後",
      :description => "クィーンエルフを倒した",
      :priority => 53,
    },
    54 => {
      :icon_id => 193,
      :title => "薔薇の名前",
      :description => "クィーンアルラウネを正気に戻した",
      :priority => 54,
    },
    55 => {
      :icon_id => 193,
      :title => "人魚との和解",
      :description => "クィーンマーメイドを倒した",
      :priority => 55,
    },
    56 => {
      :icon_id => 193,
      :title => "蜘蛛の落日",
      :description => "蜘蛛之皇女を倒した",
      :priority => 56,
    },
    57 => {
      :icon_id => 193,
      :title => "百年の孤独",
      :description => "クィーンヴァンパイアを倒した",
      :priority => 57,
    },
    58 => {
      :icon_id => 193,
      :title => "まずは文通から",
      :description => "エルフ姫からオーブを受け取った",
      :priority => 58,
    },
    59 => {
      :icon_id => 193,
      :title => "時を超えて",
      :description => "五百年前の魔王城からオーブを入手した",
      :priority => 59,
    },
    60 => {
      :icon_id => 193,
      :title => "雪の大地へ",
      :description => "ついに謎多き大陸に足を踏み込んだ",
      :priority => 60,
    },
    61 => {
      :icon_id => 193,
      :title => "三番目の熾天使",
      :description => "雪のほこらでエデンの助力を得た",
      :priority => 61,
    },
    62 => {
      :icon_id => 193,
      :title => "ぷにぷにエンジェルズ",
      :description => "二人の熾天使が復活した",
      :priority => 62,
    },
    63 => {
      :icon_id => 191,
      :title => "交わり離れる剣と闇",
      :description => "勇者の父と魔王の母、その息子とその娘のこれから",
      :priority => 63,
    },
    64 => {
      :icon_id => 191,
      :title => "わたしを離さないで",
      :description => "誰も知らず少女は戦い、世界を救った",
      :priority => 64,
    },
    65 => {
      :icon_id => 191,
      :title => "受け継がれる希望",
      :description => "滅びし世界の希望を胸に、求道者は叡智の戦いに赴く",
      :priority => 65,
    },
    66 => {
      :icon_id => 191,
      :title => "ソニアの奇妙な冒険",
      :description => "ソニアも長い冒険を乗り越えてきたようだ",
      :priority => 66,
    },
    67 => {
      :icon_id => 193,
      :title => "害虫救済",
      :description => "ゴキブリ達を救うことができた",
      :priority => 67,
    },
    68 => {
      :icon_id => 193,
      :title => "害虫絶滅",
      :description => "ゴキブリ達を救えなかった……",
      :priority => 68,
    },
    69 => {
      :icon_id => 193,
      :title => "令和たぬき合戦ぱこぱこ",
      :description => "狸と狐を和解させ戦争を防いだ",
      :priority => 69,
    },
    70 => {
      :icon_id => 193,
      :title => "引きこもりの乱、鎮圧",
      :description => "エルフの里の騒動を無事に収めた",
      :priority => 70,
    },
    71 => {
      :icon_id => 192,
      :title => "大いなる決断",
      :description => "いよいよ、大いなる決断が下される――",
      :priority => 71,
    },
    72 => {
      :icon_id => 191,
      :title => "邪神の同志として",
      :description => "アリスと共に戦う事を決意した",
      :priority => 72,
    },
    73 => {
      :icon_id => 191,
      :title => "女神の使徒として",
      :description => "イリアスと共に戦う事を決意した",
      :priority => 73,
    },
    74 => {
      :icon_id => 193,
      :title => "アルマエルマの里帰り",
      :description => "心置きなく旅立てるようだ",
      :priority => 74,
    },
    75 => {
      :icon_id => 193,
      :title => "伝説の鍛冶屋",
      :description => "ついに伝説の鍛冶屋を発見した",
      :priority => 75,
    },
    76 => {
      :icon_id => 193,
      :title => "天界到着！",
      :description => "とうとう敵地の天界へと踏み込んだ",
      :priority => 76,
    },
    77 => {
      :icon_id => 193,
      :title => "初めての天界転移",
      :description => "管理者の塔の装置を使い別大陸にワープした",
      :priority => 77,
    },
    78 => {
      :icon_id => 193,
      :title => "天界の水精",
      :description => "グランディーネに力を借りた",
      :priority => 78,
    },
    79 => {
      :icon_id => 193,
      :title => "天界の土精",
      :description => "ノーマレンに力を借りた",
      :priority => 79,
    },
    80 => {
      :icon_id => 193,
      :title => "地下組織との接触",
      :description => "反抗組織リバースクロイツの協力を取り付けた",
      :priority => 80,
    },
    81 => {
      :icon_id => 192,
      :title => "天界サバサ解放",
      :description => "ガブリエラを打ち破り、サバサを天使の支配から解放した",
      :priority => 81,
    },
    82 => {
      :icon_id => 193,
      :title => "混沌をたべちゃった！",
      :description => "天界フィノアでヌルコが思わぬ能力を示した",
      :priority => 82,
    },
    83 => {
      :icon_id => 192,
      :title => "天界コロシアム優勝",
      :description => "天界グランドノアでの武道大会に優勝した",
      :priority => 83,
    },
    84 => {
      :icon_id => 193,
      :title => "ルカ投獄",
      :description => "天界グランドノアにてサリエラに捕縛された",
      :priority => 84,
    },
    85 => {
      :icon_id => 192,
      :title => "大脱走！",
      :description => "仲間達の助けを借りてグランゴルド大監獄から脱獄した",
      :priority => 85,
    },
    86 => {
      :icon_id => 193,
      :title => "月からの襲撃者",
      :description => "天界ゴッダールにて月の民の襲撃を受けた",
      :priority => 86,
    },
    87 => {
      :icon_id => 193,
      :title => "天界の火精",
      :description => "ギガマンドラに力を借りた",
      :priority => 87,
    },
    88 => {
      :icon_id => 193,
      :title => "失われし英雄",
      :description => "罪人の封牢にてハインリヒの魂を封印した",
      :priority => 88,
    },
    89 => {
      :icon_id => 192,
      :title => "魔王の帰還",
      :description => "荒廃した魔王城に待ち望まれた主が到来した",
      :priority => 89,
    },
    90 => {
      :icon_id => 192,
      :title => "レミナ研究所の崩壊",
      :description => "レミナ研究所を破壊し、忌まわしき研究を根絶した",
      :priority => 90,
    },
    91 => {
      :icon_id => 192,
      :title => "魔王城奪還！",
      :description => "特異点世界の魔王城を天界軍の手から奪い返した",
      :priority => 91,
    },
    93 => {
      :icon_id => 193,
      :title => "レプリカントとの和解",
      :description => "ラダイト村でレプリカント達と絆を結んだ",
      :priority => 93,
    },
    94 => {
      :icon_id => 193,
      :title => "天界の風精",
      :description => "ジルフィに力を借りた",
      :priority => 94,
    },
    95 => {
      :icon_id => 193,
      :title => "ラファエラとの思わぬ共闘",
      :description => "混沌に取り込まれそうになったコスモスを倒した",
      :priority => 95,
    },
    96 => {
      :icon_id => 192,
      :title => "襲来、黒のアリス軍団！",
      :description => "黒のアリス軍団に襲撃された天界サン・イリアから脱出した",
      :priority => 96,
    },
    97 => {
      :icon_id => 193,
      :title => "謎の兄妹との別れ",
      :description => "天界グランドノアに襲来した黒のアリス軍団を撃退した",
      :priority => 97,
    },
    98 => {
      :icon_id => 193,
      :title => "怒りのリリス三姉妹",
      :description => "天界サバサに襲来した黒のアリス軍団を撃退した",
      :priority => 98,
    },
    99 => {
      :icon_id => 192,
      :title => "再起せし英雄",
      :description => "罪人の封牢にてハインリヒの魂を解放した",
      :priority => 99,
    },
    100 => {
      :icon_id => 191,
      :title => "カーテンコールと父との別れ",
      :description => "黒のアリスを撃退し、父の魂を受け継いだ",
      :priority => 100,
    },
    101 => {
      :icon_id => 193,
      :title => "人間にとっては小さな一歩だが",
      :description => "魔導船で月面へと降り立った",
      :priority => 101,
    },
    102 => {
      :icon_id => 192,
      :title => "母の助け・大陸突入編",
      :description => "月にてルシフィナの助けを取り付けた",
      :priority => 102,
    },
    103 => {
      :icon_id => 193,
      :title => "いざ、決戦の地へ！",
      :description => "アモス山からイリアス大陸へと飛び立った",
      :priority => 103,
    },
    104 => {
      :icon_id => 193,
      :title => "ミトラ封印城、解放",
      :description => "ミトラ封印城に封じられていた武具を手にした",
      :priority => 105,
    },
    105 => {
      :icon_id => 193,
      :title => "ランドルフの再起",
      :description => "絶望していた伝説の鍛冶屋ランドルフがついに奮起した",
      :priority => 106,
    },
    106 => {
      :icon_id => 192,
      :title => "イリアス神殿突入！",
      :description => "ついにイリアス神殿へと突入した",
      :priority => 107,
    },
    107 => {
      :icon_id => 191,
      :title => "天界の破壊者",
      :description => "天界ルートをクリアした",
      :priority => 108,
    },
    108 => {
      :icon_id => 193,
      :title => "魔界到着！",
      :description => "とうとう敵地の魔界へと踏み込んだ",
      :priority => 201,
    },
    109 => {
      :icon_id => 193,
      :title => "サキュバスの村の政変",
      :description => "エヴァを放逐し、サキュバスの村の実権を握った",
      :priority => 202,
    },
    110 => {
      :icon_id => 193,
      :title => "きれいなラザロ",
      :description => "反抗組織イリアスクロイツの協力を取り付けた",
      :priority => 202,
    },
    111 => {
      :icon_id => 192,
      :title => "緑の都、陥落",
      :description => "華音に勝利し、魔界グランゴルドを占領した",
      :priority => 203,
    },
    112 => {
      :icon_id => 192,
      :title => "水の都、陥落",
      :description => "禍撫に勝利し、魔界グランドノアを占領した",
      :priority => 204,
    },
    113 => {
      :icon_id => 193,
      :title => "魔界の火精",
      :description => "グリモワールに力を借りた",
      :priority => 205,
    },
    114 => {
      :icon_id => 193,
      :title => "魔界の水精",
      :description => "ガタノソアに力を借りた",
      :priority => 206,
    },
    115 => {
      :icon_id => 193,
      :title => "蛇と触手の和合",
      :description => "プランセクト村にてラミアとスキュラの講和を果たした",
      :priority => 207,
    },
    116 => {
      :icon_id => 193,
      :title => "ヤマタイ攻略作戦開始！",
      :description => "魔界エデンと手を組み、共同で魔界ヤマタイ攻略に乗り出した",
      :priority => 208,
    },
    117 => {
      :icon_id => 192,
      :title => "機械都市攻略",
      :description => "魔界ヤマタイを危機に追い込み、脱出を果たした",
      :priority => 209,
    },
    118 => {
      :icon_id => 193,
      :title => "ﾄﾘと和解せよ",
      :description => "フィノアにてハーピー族の内紛を収めた",
      :priority => 210,
    },
    119 => {
      :icon_id => 193,
      :title => "海賊新時代",
      :description => "魔界に名高いロザ海賊団を壊滅させた",
      :priority => 211,
    },
    120 => {
      :icon_id => 193,
      :title => "魔界の風精",
      :description => "アンブロシアに力を借りた",
      :priority => 212,
    },
    121 => {
      :icon_id => 192,
      :title => "人形のサーカス襲来！",
      :description => "人形のサーカスの襲撃を受けたサン・イリアから脱出した",
      :priority => 213,
    },
    122 => {
      :icon_id => 193,
      :title => "緑の都の人形劇",
      :description => "魔界グランゴルドに襲来した人形のサーカスを撃退した",
      :priority => 214,
    },
    123 => {
      :icon_id => 193,
      :title => "父との共闘",
      :description => "魔界グランドノアに襲来した人形のサーカスを撃退した",
      :priority => 215,
    },
    124 => {
      :icon_id => 193,
      :title => "機械の村の人形草子",
      :description => "魔界ヤマタイに襲来した人形のサーカスを撃退した",
      :priority => 216,
    },
    125 => {
      :icon_id => 192,
      :title => "姉との別れ",
      :description => "影紬を倒し、人形のサーカスを瓦解させた",
      :priority => 217,
    },
    126 => {
      :icon_id => 193,
      :title => "燃えろ！　サバサマン！",
      :description => "クィーンエヴァを倒し、サバサマンを仲間にした",
      :priority => 218,
    },
    127 => {
      :icon_id => 193,
      :title => "魔界の土精",
      :description => "ロアに力を借りた",
      :priority => 219,
    },
    128 => {
      :icon_id => 192,
      :title => "妖星デミウルゴス始動！",
      :description => "ついに敵の最終兵器が動き始めた",
      :priority => 220,
    },
    129 => {
      :icon_id => 193,
      :title => "迫撃！　トリプル・エデン",
      :description => "隠れ里エンリカに襲来してきた蛭蟲を撃退した",
      :priority => 221,
    },
    130 => {
      :icon_id => 193,
      :title => "これでお仕舞いです",
      :description => "黒の屋敷で影紬と黒のアリスを撃破した",
      :priority => 222,
    },
    131 => {
      :icon_id => 193,
      :title => "ソニアは存在しない",
      :description => "記憶の場所からソニアを取り戻せなかった",
      :priority => 223,
    },
    132 => {
      :icon_id => 193,
      :title => "母の助け・妖星攻略編",
      :description => "月にてルシフィナの助けを取り付けた",
      :priority => 224,
    },
    133 => {
      :icon_id => 193,
      :title => "妖星破壊",
      :description => "蛭蟲を討ち、妖星デミウルゴスを破壊した",
      :priority => 225,
    },
    134 => {
      :icon_id => 193,
      :title => "封牢の解放",
      :description => "魔界の封牢に閉じ込められていた者達を解き放った",
      :priority => 226,
    },
    135 => {
      :icon_id => 192,
      :title => "邪神城突入！",
      :description => "ついに邪神城へと突入した",
      :priority => 227,
    },
    136 => {
      :icon_id => 191,
      :title => "魔界の審判",
      :description => "魔界ルートをクリアした",
      :priority => 228,
    },
    137 => {
      :icon_id => 191,
      :title => "混沌の観察者",
      :description => "白兎の力を受け継ぎ、並行世界の記憶を継承した",
      :priority => 229,
    },
    138 => {
      :icon_id => 193,
      :title => "さよなら、次の周回で",
      :description => "それが白兎との別れとなった……この周回では",
      :priority => 104,
    },
    139 => {
      :icon_id => 191,
      :title => "第三の道",
      :description => "天界ルートと魔界ルートの仲間がついに集結した",
      :priority => 301,
    },
    140 => {
      :icon_id => 193,
      :title => "世界を救う同志として",
      :description => "智の同盟と接触し協力を得た",
      :priority => 302,
    },
    141 => {
      :icon_id => 192,
      :title => "祝福されざるもの",
      :description => "混沌の神を造り出す事に成功した",
      :priority => 303,
    },
    142 => {
      :icon_id => 193,
      :title => "一家集合！",
      :description => "両親と共に戦う時がやって来た",
      :priority => 304,
    },
    143 => {
      :icon_id => 193,
      :title => "生まれ変わった世界へ",
      :description => "深き混沌から脱出し、合一世界に降り立った",
      :priority => 305,
    },
    144 => {
      :icon_id => 193,
      :title => "折れない剣",
      :description => "ミカエラが堕天し、混沌の力を得た",
      :priority => 306,
    },
    145 => {
      :icon_id => 193,
      :title => "混沌の父の片鱗",
      :description => "混沌の力で、アンゴルモアを一時退却させた",
      :priority => 307,
    },
    146 => {
      :icon_id => 191,
      :title => "仲間を求めて",
      :description => "イリアスヴィルから新たなる旅立ちを迎えた",
      :priority => 308,
    },
    147 => {
      :icon_id => 193,
      :title => "混沌の鍛冶場オープン",
      :description => "伝説の鍛冶屋達を混沌の鍛冶場に集めよう",
      :priority => 309,
    },
    148 => {
      :icon_id => 193,
      :title => "緑からの解放",
      :description => "ガブリエラと華音を撃退し、グランゴルドを平定した",
      :priority => 310,
    },
    149 => {
      :icon_id => 193,
      :title => "粘妖の守護者",
      :description => "禍撫軍を撃退し、グランドノアを守り抜いた",
      :priority => 311,
    },
    150 => {
      :icon_id => 193,
      :title => "女王の帰還",
      :description => "行方不明になっていた女王を魔導学園で発見した",
      :priority => 312,
    },
    151 => {
      :icon_id => 193,
      :title => "肉に埋もれた城",
      :description => "蛭蟲の手からサバサを奪還した",
      :priority => 313,
    },
    152 => {
      :icon_id => 193,
      :title => "アジドル",
      :description => "アジ・ダハーカをステージから引きずり下ろした",
      :priority => 314,
    },
    153 => {
      :icon_id => 193,
      :title => "聖都灰燼",
      :description => "サン・イリアが崩壊し、結果的に騒乱の種は消えた",
      :priority => 315,
    },
    154 => {
      :icon_id => 193,
      :title => "暴走ウェポン撃退",
      :description => "ヤマタイの地で荒れ狂うマガツオオミカミを撃退した",
      :priority => 316,
    },
    155 => {
      :icon_id => 192,
      :title => "月面要塞攻略",
      :description => "月面基地でシンギュラリティを撃破した",
      :priority => 317,
    },
    156 => {
      :icon_id => 193,
      :title => "ハーピーの春",
      :description => "ハーピーの集落を守り、騒動の種を取り除いた",
      :priority => 318,
    },
    157 => {
      :icon_id => 193,
      :title => "おかえり天使たち",
      :description => "ミカエラちゃんとルシフィナちゃんが復帰した",
      :priority => 319,
    },
    158 => {
      :icon_id => 193,
      :title => "風と舞い踊る",
      :description => "風の精霊三体が戻ってきた",
      :priority => 320,
    },
    159 => {
      :icon_id => 193,
      :title => "無口でおしゃべりな土",
      :description => "土の精霊三体が戻ってきた",
      :priority => 321,
    },
    160 => {
      :icon_id => 193,
      :title => "静かな水と荒ぶる水",
      :description => "水の精霊三体が戻ってきた",
      :priority => 322,
    },
    161 => {
      :icon_id => 193,
      :title => "回り巡る炎",
      :description => "炎の精霊三体が戻ってきた",
      :priority => 323,
    },
    162 => {
      :icon_id => 192,
      :title => "僕の頭はゆうえんち",
      :description => "十二体の精霊が集結した",
      :priority => 324,
    },
    163 => {
      :icon_id => 193,
      :title => "女神復活の祈り",
      :description => "イリアス神殿で女神復活のための儀式を開始した",
      :priority => 325,
    },
    164 => {
      :icon_id => 193,
      :title => "復活した邪神！？",
      :description => "邪神城で少女アリスフィーズと合流した",
      :priority => 326,
    },
    165 => {
      :icon_id => 193,
      :title => "我等が主のために",
      :description => "封魔の洞窟で邪神復活のための儀式を開始した",
      :priority => 327,
    },
    166 => {
      :icon_id => 193,
      :title => "初心を忘れるな",
      :description => "パピが正気を取り戻した",
      :priority => 328,
    },
    167 => {
      :icon_id => 192,
      :title => "これは悲恋の物語",
      :description => "海軍や海賊と協力しワールドドロウンを撃破した",
      :priority => 329,
    },
    168 => {
      :icon_id => 192,
      :title => "胡蝶の夢",
      :description => "混沌の力を手にしたコスモスを撃破した",
      :priority => 330,
    },
    169 => {
      :icon_id => 192,
      :title => "魔芸師の罪は魔芸師が",
      :description => "ラ・クロワの助けを借りノーライフキングを撃破した",
      :priority => 331,
    },
    170 => {
      :icon_id => 192,
      :title => "大帝瞬断",
      :description => "コロシアムでアンゴルモアに打ち勝った",
      :priority => 332,
    },
    171 => {
      :icon_id => 192,
      :title => "ヤマタイの地に安寧を",
      :description => "オロチの洞に潜むマガツオオミカミを滅ぼした",
      :priority => 333,
    },
    172 => {
      :icon_id => 193,
      :title => "妖星陥落",
      :description => "妖星デミウルゴスにて蛭蟲・禍撫・華音を撃破した",
      :priority => 334,
    },
    173 => {
      :icon_id => 192,
      :title => "お前らはモリを出ろ",
      :description => "植物族の力を借りバアル・ゼブブを撃退した",
      :priority => 335,
    },
    174 => {
      :icon_id => 193,
      :title => "四人組の再更生",
      :description => "ヴァニラ達四人を「強欲」の力から解き放った",
      :priority => 336,
    },
    175 => {
      :icon_id => 193,
      :title => "怠惰の克服",
      :description => "ルミを「怠惰」の力から解き放った",
      :priority => 337,
    },
    176 => {
      :icon_id => 193,
      :title => "嫉妬の連鎖",
      :description => "リリィを「嫉妬」の力から解き放った",
      :priority => 338,
    },
    177 => {
      :icon_id => 193,
      :title => "アンガーマネジメント",
      :description => "牛魔王を「憤怒」の力から解き放った",
      :priority => 339,
    },
    178 => {
      :icon_id => 193,
      :title => "満ち足りた食欲",
      :description => "カサンドラを「暴食」の力から解き放った",
      :priority => 340,
    },
    179 => {
      :icon_id => 193,
      :title => "溢れ出る色欲",
      :description => "ウィッチサキュバスを「色欲」の力から解き放った",
      :priority => 341,
    },
    180 => {
      :icon_id => 193,
      :title => "高慢と偏見とヴァンパイア",
      :description => "クィーンヴァンパイアを「傲慢」の力から解き放った",
      :priority => 342,
    },
    181 => {
      :icon_id => 192,
      :title => "罪と罰",
      :description => "大罪の殿堂で七つの大罪を撃破した",
      :priority => 343,
    },
    182 => {
      :icon_id => 193,
      :title => "巡り廻る人形遣いの因果",
      :description => "影紬の新しいボディを完成させた",
      :priority => 344,
    },
    183 => {
      :icon_id => 192,
      :title => "全てを識らざる者",
      :description => "光の塔と闇の塔で全てを識る者を撃破した",
      :priority => 345,
    },
    184 => {
      :icon_id => 192,
      :title => "たのしい女体のたび",
      :description => "リリスの体内に潜り込んだエキドナクィーンを撃破した",
      :priority => 347,
    },
    185 => {
      :icon_id => 192,
      :title => "クトゥルフの呼び声",
      :description => "ルルイエで名状しがたきものを撃退した",
      :priority => 348,
    },
    186 => {
      :icon_id => 192,
      :title => "侵蝕された侵蝕者",
      :description => "侵蝕された妖星で次元侵蝕者を滅ぼした",
      :priority => 349,
    },
    187 => {
      :icon_id => 192,
      :title => "不滅を滅ぼすもの",
      :description => "ゴルド火山でダークフェニックスを撃破した",
      :priority => 350,
    },
    188 => {
      :icon_id => 192,
      :title => "銀河魔神の逆襲",
      :description => "迫り来る星喰いを月面基地で撃破した",
      :priority => 351,
    },
    189 => {
      :icon_id => 193,
      :title => "混沌に満ちた塔で",
      :description => "管理者の塔でヌルコを助け出した",
      :priority => 352,
    },
    190 => {
      :icon_id => 193,
      :title => "究極のトリニティ",
      :description => "三人のエデンが合一し究極形態となった",
      :priority => 357,
    },
    191 => {
      :icon_id => 193,
      :title => "全てを受け入れた勇者",
      :description => "ハインリヒが己自身を受け入れ、真の勇者となった",
      :priority => 358,
    },
    192 => {
      :icon_id => 192,
      :title => "千年の孤独",
      :description => "黒の屋敷にて黒のアリスを撃破した",
      :priority => 359,
    },
    193 => {
      :icon_id => 191,
      :title => "おかえり、ソニア",
      :description => "ソニアが仲間に復帰した",
      :priority => 360,
    },
    194 => {
      :icon_id => 193,
      :title => "ちょっと怖い姉",
      :description => "アドラメレクを仲間にした",
      :priority => 361,
    },
    195 => {
      :icon_id => 193,
      :title => "導く者と死の管理者",
      :description => "白兎と死神を仲間にした",
      :priority => 362,
    },
    196 => {
      :icon_id => 192,
      :title => "さらば最強の戦士",
      :description => "蓬莱山で虚竜を撃破した",
      :priority => 363,
    },
    197 => {
      :icon_id => 192,
      :title => "邪神を継ぎし者",
      :description => "アリスが邪神の力を受け継いだ",
      :priority => 364,
    },
    198 => {
      :icon_id => 192,
      :title => "創世の女神ついに降臨",
      :description => "イリアスが真の力を取り戻した",
      :priority => 365,
    },
    199 => {
      :icon_id => 193,
      :title => "正史の息子たち",
      :description => "ネロとネリスを仲間にした",
      :priority => 366,
    },
    200 => {
      :icon_id => 192,
      :title => "ジハードバスター",
      :description => "三闘神を全員撃破した",
      :priority => 367,
    },
    201 => {
      :icon_id => 191,
      :title => "破滅に打ち勝つ者",
      :description => "十六の破滅事象を全て討ち倒した",
      :priority => 368,
    },
    202 => {
      :icon_id => 191,
      :title => "さよなら、混沌の父娘",
      :description => "混沌の父娘は長い旅へと出かけた",
      :priority => 369,
    },
    203 => {
      :icon_id => 4755,
      :title => "混沌を晴らす者",
      :description => "混沌が晴れ世界が平和になった",
      :priority => 370,
    },
    204 => {
      :icon_id => 193,
      :title => "魔法少女ぐらん☆べりあ",
      :description => "グランベリアは悪夢に打ち勝ち魔法少女となった",
      :priority => 346,
    },
    205 => {
      :icon_id => 193,
      :title => "怪盗騒ぎ、終幕",
      :description => "三つの指輪を手に入れ、二人の大怪盗が仲間になった",
      :priority => 355,
    },
    206 => {
      :icon_id => 193,
      :title => "復興への第一歩",
      :description => "イリアス神殿に人が集まり、復興が始まった",
      :priority => 353,
    },
    207 => {
      :icon_id => 193,
      :title => "スサノオの末裔",
      :description => "狐華の出自が明らかになり、仲間になった",
      :priority => 354,
    },
    208 => {
      :icon_id => 193,
      :title => "倫理は浜で死にました",
      :description => "ナタリア大陸北岸への魔物漂着事件は内輪の仕業だった",
      :priority => 356,
    },
    209 => {
      :icon_id => 193,
      :title => "コンプライアンス僧侶",
      :description => "確かに肌の露出はほとんどない",
      :priority => 371,
    },
    210 => {
      :icon_id => 193,
      :title => "職無キ者",
      :description => "それでもやはり無職は無職",
      :priority => 372,
    },

#==============================================================================
    # 買い物金額
    1001 => {
      :icon_id => 193,
      :title => "初めてのお買い物",
      :description => "初めて店でモノを買った",
      :priority => 1001,    
    },
    1002 => {
      :icon_id => 193,
      :title => "店屋の常連",
      :description => "買い物額30,000G達成、すっかり店屋の顔なじみ",
      :priority => 1002,    
    },
    1003 => {
      :icon_id => 192,
      :title => "店屋のキング",
      :description => "買い物額300,000G達成、地域経済に貢献",
      :priority => 1003,    
    },
    1004 => {
      :icon_id => 191,
      :title => "買い物クレイジー",
      :description => "買い物使用額3,000,000G達成、買い物を極める",
      :priority => 1004,    
    },
    1005 => {
      :icon_id => 191,
      :title => "買い物マスター",
      :description => "買い物使用額30,000,000G達成、買い物をマスターする",
      :priority => 1005,    
    },
    # 鍛冶利用数
    1011 => {
      :icon_id => 193,
      :title => "初めての鍛冶",
      :description => "初めて鍛冶屋でモノを作ってもらった",
      :priority => 1011,    
    },
    1012 => {
      :icon_id => 193,
      :title => "駆け出し鍛冶ヤー",
      :description => "鍛冶を50回頼み、だいぶ慣れてきた",
      :priority => 1012,    
    },
    1013 => {
      :icon_id => 192,
      :title => "鍛冶マニア",
      :description => "鍛冶を200回頼み、すっかり虜になった",
      :priority => 1013,    
    },
    1014 => {
      :icon_id => 191,
      :title => "鍛冶王",
      :description => "鍛冶を500回頼み、もはや王となった",
      :priority => 1014,    
    },
    1015 => {
      :icon_id => 191,
      :title => "鍛冶神",
      :description => "鍛冶を1000回頼み、神として崇められた",
      :priority => 1015,    
    },
    # 転職回数
    1021 => {
      :icon_id => 193,
      :title => "初めての転職",
      :description => "初めてイリアス神殿で転職した",
      :priority => 1021,    
    },
    1022 => {
      :icon_id => 193,
      :title => "そこそこ転職ヤー",
      :description => "10回転職し、職業のなんたるかを掴んだ",
      :priority => 1022,    
    },
    1023 => {
      :icon_id => 192,
      :title => "ハンドレッド・リクルート",
      :description => "100回転職し、イリアス神殿の常連となった",
      :priority => 1023,    
    },
    1024 => {
      :icon_id => 191,
      :title => "転職王",
      :description => "400回転職し、就職業界にその名を轟かせた",
      :priority => 1024,    
    },
    1025 => {
      :icon_id => 191,
      :title => "インフィニット・リクルート",
      :description => "1000回転職し、職という概念さえ破壊した",
      :priority => 1025,    
    },
    # 転種回数
    1031 => {
      :icon_id => 193,
      :title => "初めての転種",
      :description => "初めてイリアス神殿で転種した",
      :priority => 1031,    
    },
    1032 => {
      :icon_id => 193,
      :title => "それなり転種ヤー",
      :description => "5回転種し、種族について分かってきた",
      :priority => 1032,    
    },
    1033 => {
      :icon_id => 192,
      :title => "シェイプシフター",
      :description => "50回転種し、自分の種族が分からなくなってきた",
      :priority => 1033,    
    },
    1034 => {
      :icon_id => 191,
      :title => "転種モラトリアム",
      :description => "200回転種し、真の自分を見定めた",
      :priority => 1034,    
    },
    1035 => {
      :icon_id => 191,
      :title => "転種ゴッド",
      :description => "500回転種し、神の座まで辿り着いた",
      :priority => 1035,    
    },
    # 戦闘回数
    1041 => {
      :icon_id => 193,
      :title => "初めてのバトル！",
      :description => "初めて敵と戦った、忘れられない思い出",
      :priority => 1041,    
    },
    1042 => {
      :icon_id => 193,
      :title => "いっぱし冒険者",
      :description => "300回のバトルをこなせば、冒険者としてなかなかだ",
      :priority => 1042,    
    },
    1043 => {
      :icon_id => 192,
      :title => "熟練の勇者",
      :description => "2000回もバトルをこなせば、勇者として比類ない",
      :priority => 1043,    
    },
    1044 => {
      :icon_id => 191,
      :title => "世界の救世主",
      :description => "5000回も戦えば、世界だって救えるはず",
      :priority => 1044,    
    },
    1045 => {
      :icon_id => 191,
      :title => "究極戦闘者",
      :description => "10000回ものバトルで究極の戦闘者となった",
      :priority => 1045,    
    },
    # 逃亡回数
    1051 => {
      :icon_id => 193,
      :title => "初めての逃亡",
      :description => "初めて敵に背中を見せた屈辱の思い出",
      :priority => 1051,    
    },
    1052 => {
      :icon_id => 193,
      :title => "自由からの逃走",
      :description => "10回逃走し、逃げるのにも慣れてきた",
      :priority => 1052,    
    },
    1053 => {
      :icon_id => 192,
      :title => "逃げてばかりの人生",
      :description => "50回逃走し、人生からも逃げそうだ",
      :priority => 1053,    
    },
    1054 => {
      :icon_id => 191,
      :title => "逃げるが勝ち",
      :description => "150回逃走し、もはや勝った気分になった",
      :priority => 1054,    
    },
    1055 => {
      :icon_id => 191,
      :title => "逃走こそ闘争",
      :description => "500回逃走した、逃げる事こそ戦いだ！",
      :priority => 1055,    
    },
    # 敗北回数
    1061 => {
      :icon_id => 193,
      :title => "初めての敗北",
      :description => "敵に敗北し、ご褒美……いや、辱めを受けた",
      :priority => 1061,    
    },
    1062 => {
      :icon_id => 193,
      :title => "冒険する餌",
      :description => "30回敗北し、その数だけ餌食にされた",
      :priority => 1062,    
    },
    1063 => {
      :icon_id => 192,
      :title => "たたかうひもの",
      :description => "100回敗北し、魔物に養分を与えた",
      :priority => 1063,    
    },
    1064 => {
      :icon_id => 191,
      :title => "負け癖勇者",
      :description => "300回敗北し、完全に負け癖がついた",
      :priority => 1064,    
    },
    1065 => {
      :icon_id => 191,
      :title => "負ければ妖女に犯される",
      :description => "500回敗北し、タイトル回収を果たした",
      :priority => 1065,    
    },
    # 総撃破数
    1071 => {
      :icon_id => 193,
      :title => "魔物キラー",
      :description => "襲い来る敵500体を返り討ちにした",
      :priority => 1071,    
    },
    1072 => {
      :icon_id => 192,
      :title => "魔物バスター",
      :description => "襲い来る敵5000体を排除した",
      :priority => 1072,    
    },
    1073 => {
      :icon_id => 191,
      :title => "魔物クラッシャー",
      :description => "襲い来る敵10000体を叩き潰した",
      :priority => 1073,    
    },
    1074 => {
      :icon_id => 191,
      :title => "魔物絶滅者",
      :description => "襲い来る敵30000体を討滅し尽くした",
      :priority => 1074,    
    },
    # 職業公開率
    1201 => {
      :icon_id => 191,
      :title => "職業100%達成",
      :description => "職業100パーセント達成",
      :priority => 1201,    
    },
    # 種族公開率
    1202 => {
      :icon_id => 191,
      :title => "種族100%達成",
      :description => "種族100パーセント達成",
      :priority => 1202,    
    },
    # キャラ図鑑コンプ率
    1301 => {
      :icon_id => 191,
      :title => "キャラ図鑑100%達成",
      :description => "キャラ図鑑100パーセント達成",
      :priority => 1301,    
    },
    # 魔物図鑑コンプ率
    1311 => {
      :icon_id => 191,
      :title => "魔物図鑑100%達成",
      :description => "魔物図鑑100パーセント達成",
      :priority => 1311,    
    },
    # 武器図鑑コンプ率
    1321 => {
      :icon_id => 191,
      :title => "武器図鑑100%達成",
      :description => "武器図鑑100パーセント達成",
      :priority => 1321,    
    },
    # 防具図鑑コンプ率
    1331 => {
      :icon_id => 191,
      :title => "防具図鑑100%達成",
      :description => "防具図鑑100パーセント達成",
      :priority => 1331,    
    },
    # アクセサリ図鑑コンプ率
    1341 => {
      :icon_id => 191,
      :title => "アクセサリ図鑑100%達成",
      :description => "アクセサリ図鑑100パーセント達成",
      :priority => 1341,    
    },
    # アイテム図鑑コンプ率
    1351 => {
      :icon_id => 191,
      :title => "アイテム図鑑100%達成",
      :description => "アイテム図鑑100パーセント達成",
      :priority => 1351,    
    },
    # 全体収集率
    1371 => {
      :icon_id => 191,
      :title => "全体収集率100%達成",
      :description => "全体収集率100パーセント達成",
      :priority => 1371,    
    },
#==============================================================================
    1401 => {
      :icon_id => 193,
      :title => "メダルビギナー",
      :description => "小さなメダルを集め始めたばかり",
      :priority => 1401,    
    },
    1402 => {
      :icon_id => 193,
      :title => "メダルコレクター",
      :description => "メダル女王様に名を覚えてもらった",
      :priority => 1402,    
    },
    1403 => {
      :icon_id => 192,
      :title => "メダルマニア",
      :description => "小さなメダル交換の虜になった",
      :priority => 1403,    
    },
    1404 => {
      :icon_id => 191,
      :title => "メダルマスター",
      :description => "小さなメダルをひたすらに交換し続けた",
      :priority => 1404,    
    },
    1406 => {
      :icon_id => 193,
      :title => "大メダルビギナー",
      :description => "大きなメダルを集め始めたばかり",
      :priority => 1406,    
    },
    1407 => {
      :icon_id => 193,
      :title => "大メダルコレクター",
      :description => "メダル王様の常連となった",
      :priority => 1407,    
    },
    1408 => {
      :icon_id => 192,
      :title => "大メダルマニア",
      :description => "大きなメダル交換の虜になった",
      :priority => 1408,    
    },
    1409 => {
      :icon_id => 192,
      :title => "大メダルマスター",
      :description => "大きなメダルをひたすらに交換し続けた",
      :priority => 1409,    
    },
    1411 => {
      :icon_id => 193,
      :title => "BF初勝利",
      :description => "初めてバトルファックで勝利した",
      :priority => 1411,    
    },
    1412 => {
      :icon_id => 193,
      :title => "一人前バトルファッカー",
      :description => "15人のバトルファッカーを破った",
      :priority => 1412,    
    },
    1413 => {
      :icon_id => 192,
      :title => "ベテランバトルファッカー",
      :description => "30人のバトルファッカーを破った",
      :priority => 1413,    
    },
    1414 => {
      :icon_id => 191,
      :title => "マスターバトルファッカー",
      :description => "52人のバトルファッカーを破った",
      :priority => 1414,    
    },
    1415 => {
      :icon_id => 191,
      :title => "快楽を極めし者",
      :description => "BF神を破り、快楽を極めし者となった",
      :priority => 1415,    
    },
    1421 => {
      :icon_id => 193,
      :title => "BF初敗北",
      :description => "初めてバトルファックで敗北した",
      :priority => 1421,    
    },
    1422 => {
      :icon_id => 193,
      :title => "無様な敗者",
      :description => "バトルファックに30回敗北した",
      :priority => 1422,    
    },
    1423 => {
      :icon_id => 192,
      :title => "敗北の味",
      :description => "バトルファックに50回敗北し、負けの味にはまった",
      :priority => 1423,    
    },
    1501 => {
      :icon_id => 193,
      :title => "ヴァニラの小さなお店",
      :description => "薬草が扱えて、初めて道具屋だ",
      :priority => 1501,    
    },
    1502 => {
      :icon_id => 193,
      :title => "そこそこのお店",
      :description => "個人規模の道具屋として十分だ",
      :priority => 1502,    
    },
    1503 => {
      :icon_id => 192,
      :title => "一人前のお店",
      :description => "セントラ大陸でもやっていける品揃えだ",
      :priority => 1503,    
    },
    1504 => {
      :icon_id => 192,
      :title => "ヴァニラの大商店",
      :description => "世界でも指折りの大商店だ",
      :priority => 1504,    
    },
    1505 => {
      :icon_id => 191,
      :title => "商業王ヴァニラ",
      :description => "ヴァニラのおみせが世界の頂点に君臨した",
      :priority => 1505,    
    },
    1511 => {
      :icon_id => 193,
      :title => "パピの鍛冶屋",
      :description => "鍛冶屋として、なかなかの一歩",
      :priority => 1511,    
    },
    1512 => {
      :icon_id => 192,
      :title => "一流の鍛冶屋",
      :description => "遠くからもお客が来るレベルだ",
      :priority => 1512,    
    },
    1513 => {
      :icon_id => 192,
      :title => "鍛冶屋五本の指",
      :description => "世界でも五本の指の数えられる腕前だ",
      :priority => 1513,    
    },
    1514 => {
      :icon_id => 191,
      :title => "世界一の鍛冶屋",
      :description => "パピが世界一の鍛冶屋となった",
      :priority => 1514,    
    },
    # 親方関連
    1520 => {
      :icon_id => 193,
      :title => "スーパー親方",
      :description => "鍛冶レベルが4まで上がった",
      :priority => 1520,
    },
    1521 => {
      :icon_id => 192,
      :title => "ウルトラ親方",
      :description => "鍛冶レベルが8まで上がった",
      :priority => 1521,
    },
    1522 => {
      :icon_id => 191,
      :title => "アルティメット親方",
      :description => "鍛冶レベルが最大まで上がった",
      :priority => 1522,
    },
    1524 => {
      :icon_id => 191,
      :title => "親方を集めし者",
      :description => "世界中に散った親方を全員発見した",
      :priority => 1524,
    },
    # コロシアム
    1601 => {
      :icon_id => 193,
      :title => "ビギナー級制覇",
      :description => "コロシアムでビギナー級を制覇した",
      :priority => 1601,    
    },
    1602 => {
      :icon_id => 193,
      :title => "プロフェッショナル級制覇",
      :description => "コロシアムでプロフェッショナル級を制覇した",
      :priority => 1602,    
    },
    1603 => {
      :icon_id => 192,
      :title => "チャンピオン級制覇",
      :description => "コロシアムでチャンピオン級を制覇した",
      :priority => 1603,    
    },
    1604 => {
      :icon_id => 191,
      :title => "アンリミテッド級制覇",
      :description => "コロシアムでアンリミテッド級を制覇した",
      :priority => 1604,    
    },
    1605 => {
      :icon_id => 191,
      :title => "アルティメイト級制覇",
      :description => "コロシアムでアルティメイト級を制覇した",
      :priority => 1605,    
    },
    1606 => {
      :icon_id => 191,
      :title => "カオス級制覇",
      :description => "コロシアムでカオス級を制覇した",
      :priority => 1606,    
    },
    1611 => {
      :icon_id => 193,
      :title => "種族別通常杯制覇",
      :description => "コロシアムで種族別通常タイトルひとつを制覇した",
      :priority => 1611,    
    },
    1612 => {
      :icon_id => 192,
      :title => "種族別上級杯制覇",
      :description => "コロシアムで種族別上級タイトルひとつを制覇した",
      :priority => 1612,    
    },
    1613 => {
      :icon_id => 191,
      :title => "種族別最上級杯制覇",
      :description => "コロシアムで種族別最上級タイトルひとつを制覇した",
      :priority => 1613,    
    },
    1614 => {
      :icon_id => 191,
      :title => "種族別究極杯制覇",
      :description => "コロシアムで種族別究極タイトルひとつを制覇した",
      :priority => 1614,    
    },
#==============================================================================
    2000 => {
      :icon_id => 193,
      :title => "フリーダム",
      :description => "冒険は自由であるものだ",
      :priority => 2000,
    },
    2001 => {
      :icon_id => 192,
      :title => "ストライクフリーダム",
      :description => "ルカ、心のままに",
      :priority => 2001,
    },
    2005 => {
      :icon_id => 192,
      :title => "ネロ必死だな",
      :description => "通りすがりは大失敗したようだ",
      :priority => 2005,
    },
    2006 => {
      :icon_id => 193,
      :title => "アミラ斬殺",
      :description => "どうせ何事もなかったように復活する",
      :priority => 2006,
    },
    2007 => {
      :icon_id => 191,
      :title => "ブルジョアジー",
      :description => "超豪華宿に泊まり、金持ち気分を満喫した",
      :priority => 2007,
    },
    2008 => {
      :icon_id => 193,
      :title => "魔女狩りの村のコウモリ",
      :description => "あなたはいつでもキョロキョロ",
      :priority => 2008,
    },
    2009 => {
      :icon_id => 193,
      :title => "犬娘の悟り",
      :description => "悟りを開いても、骨付き肉は大好き",
      :priority => 2009,
    },
    2010 => {
      :icon_id => 193,
      :title => "羊をめぐる冒険",
      :description => "世界の酒場で目撃される酔っ払い羊",
      :priority => 2010,
    },
    2011 => {
      :icon_id => 193,
      :title => "仲良し二人",
      :description => "ヌルコとノームは友情を感じている……",
      :priority => 2011,
    },
    2012 => {
      :icon_id => 191,
      :title => "スロットマスター",
      :description => "スロットで777を出した",
      :priority => 2012,
    },
    2013 => {
      :icon_id => 191,
      :title => "バトル・イン・777",
      :description => "戦闘中に777を出した",
      :priority => 2013,
    },
    2014 => {
      :icon_id => 191,
      :title => "ポーカーマスター",
      :description => "ポーカーでRSFを出した",
      :priority => 2014,
    },
    2015 => {
      :icon_id => 191,
      :title => "バトル・イン・RSF",
      :description => "戦闘中にRSFを出した",
      :priority => 2015,
    },
    2016 => {
      :icon_id => 193,
      :title => "なぐりあい宇宙",
      :description => "君は、星の涙を見る",
      :priority => 2016,
    },
    2017 => {
      :icon_id => 193,
      :title => "重力に挑む小悪魔",
      :description => "身投げインプの噂があるようだ……",
      :priority => 2017,
    },
    2018 => {
      :icon_id => 193,
      :title => "ちぃぱっぱ",
      :description => "あたまのおはながちぃぱっぱ",
      :priority => 2018,
    },
    2020 => {
      :icon_id => 193,
      :title => "私を探して……",
      :description => "町に潜んでいるアミラを発見した",
      :priority => 2020,
    },
    2021 => {
      :icon_id => 192,
      :title => "15番目のアミラ",
      :description => "15匹のアミラを発見した",
      :priority => 2021,
    },
    2022 => {
      :icon_id => 192,
      :title => "25人のヘビー・アミラン",
      :description => "25匹のアミラを発見した",
      :priority => 2022,
    },
    2031 => {
      :icon_id => 193,
      :title => "パンツの第一歩",
      :description => "パンツ先生に初めてパンツを見せた",
      :priority => 2031,
    },
    2032 => {
      :icon_id => 192,
      :title => "パンツコレクター",
      :description => "パンツ先生に50枚のパンツを見せた",
      :priority => 2032,
    },
    2033 => {
      :icon_id => 192,
      :title => "パンツマスター",
      :description => "パンツ先生に120枚のパンツを見せた",
      :priority => 2033,
    },
    2034 => {
      :icon_id => 192,
      :title => "パンツ王",
      :description => "パンツ先生に200枚のパンツを見せた",
      :priority => 2034,
    },
    2035 => {
      :icon_id => 191,
      :title => "パンツゴッド",
      :description => "ありがとう……それしか言う言葉がみつからない",
      :priority => 2035,
    },
    2039 => {
      :icon_id => 191,
      :title => "パンツ先生死去",
      :description => "その死に世界中の変態が涙した",
      :priority => 2039,
    },
    2101 => {
      :icon_id => 193,
      :title => "グリーンな職場",
      :description => "新たなクィーンアルラウネが誕生した",
      :priority => 2101,
    },
    2102 => {
      :icon_id => 193,
      :title => "エルの社会勉強",
      :description => "クィーンマーメイドに一歩近付いたかもしれない",
      :priority => 2102,
    },
    2103 => {
      :icon_id => 193,
      :title => "虫の女王",
      :description => "めでたくクィーンインセクトが決定した",
      :priority => 2103,
    },
    2104 => {
      :icon_id => 193,
      :title => "真名ゲレゲレ",
      :description => "吸血鬼パブの成功を祝し、ヴァニラは真名を授かった",
      :priority => 2104,
    },
    2105 => {
      :icon_id => 193,
      :title => "魔導王の決意",
      :description => "グランゴルド王は迷いを克服した",
      :priority => 2105,
    },
    2106 => {
      :icon_id => 193,
      :title => "美しき世界",
      :description => "二人の熾天使は自然の素晴らしさを知った",
      :priority => 2106,
    },
    2107 => {
      :icon_id => 193,
      :title => "霊化ルシア",
      :description => "人体をエレメンタル化する秘技を開発した",
      :priority => 2107,
    },
    2108 => {
      :icon_id => 193,
      :title => "グロリア海賊団壊滅",
      :description => "グロリア海賊団をバトルファックで撃退した",
      :priority => 2108,
    },
    2109 => {
      :icon_id => 193,
      :title => "正体不明のメダル王",
      :description => "初代メダル王を発見した",
      :priority => 2109,
    },
    2110 => {
      :icon_id => 193,
      :title => "シロクマヘルパーズ",
      :description => "迷子のシロクマ娘を里に送ってあげた",
      :priority => 2110,
    },
    2111 => {
      :icon_id => 193,
      :title => "値切られ三姉妹",
      :description => "カナン三姉妹を値切り、おまけまでもらった",
      :priority => 2111,
    },
    2112 => {
      :icon_id => 193,
      :title => "自分を抹消",
      :description => "死神に抹消されてしまった",
      :priority => 2112,
    },
    2113 => {
      :icon_id => 193,
      :title => "やっと分かった？",
      :description => "エデンはようやく過ちを知った",
      :priority => 2113,
    },
    2114 => {
      :icon_id => 192,
      :title => "拳と淫魔",
      :description => "アルマエルマに力を認められた",
      :priority => 2114,
    },
    2115 => {
      :icon_id => 192,
      :title => "種族の垣根を越えて",
      :description => "異種への転種が可能になった",
      :priority => 2115,
    },
    2116 => {
      :icon_id => 193,
      :title => "こっ！　これは！",
      :description => "エッチな本を読んだ",
      :priority => 2116,
    },
    2117 => {
      :icon_id => 193,
      :title => "アリよさらば",
      :description => "アリクイ娘は過去の罪と向き合った",
      :priority => 2117,
    },
    2118 => {
      :icon_id => 193,
      :title => "うさうさアロー",
      :description => "ウサギ娘はエルフの秘技を身につけた",
      :priority => 2118,
    },
    2119 => {
      :icon_id => 193,
      :title => "竜宮ダンス☆",
      :description => "サキ達は海に伝わる踊りを習得した",
      :priority => 2119,
    },
    2120 => {
      :icon_id => 191,
      :title => "夜の国と七つの世界の勇者達",
      :description => "夢の主を倒し、大事件を解決した",
      :priority => 2120,
    },
    2121 => {
      :icon_id => 191,
      :title => "七つの世界の悪夢達",
      :description => "同盟者達を全員仲間にした",
      :priority => 2121,
    },
    2122 => {
      :icon_id => 192,
      :title => "疫病退散アマビエ様",
      :description => "アマビエ様が民を救済した",
      :priority => 2122,
    },
    2123 => {
      :icon_id => 192,
      :title => "逆襲のカサンドラ",
      :description => "全力のカサンドラを討伐した",
      :priority => 2123,
    },
    2124 => {
      :icon_id => 191,
      :title => "プロメスティンズ・ゲート",
      :description => "時間ループを解消した",
      :priority => 2124,
    },
    2125 => {
      :icon_id => 191,
      :title => "楽しいお祭り",
      :description => "ヤマタイの夜祭を楽しんだ",
      :priority => 2125,
    },
    2126 => {
      :icon_id => 193,
      :title => "借りてきた土の子",
      :description => "玉藻の依頼をクリアした",
      :priority => 2126,
    },
    2127 => {
      :icon_id => 193,
      :title => "天界の薔薇",
      :description => "華音の依頼をクリアした",
      :priority => 2127,
    },
    2128 => {
      :icon_id => 193,
      :title => "天界で最も美味いモノ",
      :description => "蛭蟲の依頼をクリアした",
      :priority => 2128,
    },
    2129 => {
      :icon_id => 193,
      :title => "カナデ様へのプレゼント",
      :description => "禍撫に贈り物をした",
      :priority => 2129,
    },
    2130 => {
      :icon_id => 193,
      :title => "魔王よ、強くあれ",
      :description => "沙蛇に託された品を受け取った",
      :priority => 2130,
    },
    2131 => {
      :icon_id => 193,
      :title => "ルカよ、魔王に寄り添う者であれ",
      :description => "魅凪に託された品を受け取った",
      :priority => 2131,
    },
    2132 => {
      :icon_id => 193,
      :title => "むっつりスケベ",
      :description => "ラファエラの依頼をクリアした",
      :priority => 2132,
    },
    2133 => {
      :icon_id => 193,
      :title => "神武器の回収",
      :description => "ガブリエラの依頼をクリアした",
      :priority => 2133,
    },
    2134 => {
      :icon_id => 193,
      :title => "機械兵器マニア",
      :description => "ウリエラの依頼をクリアした",
      :priority => 2134,
    },
    2135 => {
      :icon_id => 193,
      :title => "サリエラの笑顔",
      :description => "サリエラに古代寿司を食べさせてあげた",
      :priority => 2135,
    },
    2136 => {
      :icon_id => 193,
      :title => "変なマスコット人形",
      :description => "姉妹天使の依頼をクリアした",
      :priority => 2136,
    },
    2137 => {
      :icon_id => 192,
      :title => "合体、ぼくらのサバサ王！",
      :description => "魂の断片を揃え、サバサ王を仲間にした",
      :priority => 2137,
    },
    2138 => {
      :icon_id => 191,
      :title => "邪神の究極生体兵器",
      :description => "ギガントウェポンを仲間にした",
      :priority => 2138,
    },
    2139 => {
      :icon_id => 191,
      :title => "女神の究極生体兵器",
      :description => "ネフィリムウェポンを仲間にした",
      :priority => 2139,
    },
    2140 => {
      :icon_id => 193,
      :title => "エリクサーちょうだい！",
      :description => "エルフ屋敷のマジックポットを叩きのめした",
      :priority => 2140,
    },
    2141 => {
      :icon_id => 193,
      :title => "家族消沈",
      :description => "ルカ一家の社会性の無さが示された",
      :priority => 2141,
    },
    2142 => {
      :icon_id => 193,
      :title => "世界最高峰制覇",
      :description => "世界最高峰の蓬莱山を制覇したが、空は飛べなかった",
      :priority => 2142,
    },
    2143 => {
      :icon_id => 193,
      :title => "宇宙を駆ける",
      :description => "空は飛べないが、世界初の宇宙遊泳を果たした",
      :priority => 2143,
    },
    2144 => {
      :icon_id => 193,
      :title => "勇者の挫折1",
      :description => "1と数字がついている時点で、二度目があるのは明らかだ",
      :priority => 2145,
    },
    2145 => {
      :icon_id => 193,
      :title => "勇者の挫折2",
      :description => "二度の挫折の後、北の勇者は己を見つめ直した",
      :priority => 2146,
    },
    2146 => {
      :icon_id => 193,
      :title => "勇者の挫折3",
      :description => "またも自身の弱さを思い知ったが、北の勇者は晴れやかだった",
      :priority => 2147,
    },
    2147 => {
      :icon_id => 193,
      :title => "北の勇者、旅立ち",
      :description => "北の勇者は世界を救う冒険に旅立った",
      :priority => 2148,
    },
    2148 => {
      :icon_id => 193,
      :title => "ゆうべはおたのしみでしたね",
      :description => "トランプをしたり枕投げをしたり、その他色々と楽しんだ",
      :priority => 2149,
    },
    2149 => {
      :icon_id => 193,
      :title => "銀河のヒーロー",
      :description => "コズミックウーマンが仲間になってくれた",
      :priority => 2144,
    },
    2150 => {
      :icon_id => 191,
      :title => "全ての封印を解きし者",
      :description => "ミトラ封印城の全ての封印を解いた",
      :priority => 2150,
    },
    2151 => {
      :icon_id => 191,
      :title => "楽曲コンプリート",
      :description => "全てのCDを集めた",
      :priority => 2151,
    },
    2152 => {
      :icon_id => 191,
      :title => "宝剣を携えし者",
      :description => "妖精の島で二振りの宝剣を受け取った",
      :priority => 2152,
    },
    2153 => {
      :icon_id => 191,
      :title => "異種間転種を網羅せし者",
      :description => "全ての異種間転種が可能になった",
      :priority => 2153,
    },
    2154 => {
      :icon_id => 193,
      :title => "未知との遭遇",
      :description => "月面で謎の知的生命体に遭遇した",
      :priority => 2154,
    },
    2155 => {
      :icon_id => 191,
      :title => "クロスオーバーイベント",
      :description => "世界のヒーロー達が集結した",
      :priority => 2155,
    },
    2156 => {
      :icon_id => 191,
      :title => "アポロの置き土産",
      :description => "今も月には忘れられた国の旗が立つ",
      :priority => 2156,
    },

#==============================================================================
    3001 => {
      :icon_id => 191,
      :title => "天使殺し殺し",
      :description => "鎧の狂戦士を倒した",
      :priority => 3001,
    },
    3002 => {
      :icon_id => 192,
      :title => "七転び八起き",
      :description => "七尾を倒した",
      :priority => 3002,
    },
    3003 => {
      :icon_id => 192,
      :title => "なぞなぞ嫌い",
      :description => "スフィンクスを倒した",
      :priority => 3003,
    },
    3004 => {
      :icon_id => 192,
      :title => "魔王退治？",
      :description => "冥府アリスを倒した",
      :priority => 3004,
    },
    3005 => {
      :icon_id => 191,
      :title => "死に打ち勝った者",
      :description => "死神を倒した",
      :priority => 3005,
    },
    3006 => {
      :icon_id => 191,
      :title => "大海の覇者",
      :description => "リヴァイアサンを倒した",
      :priority => 3006,
    },
    3007 => {
      :icon_id => 191,
      :title => "火中に立ちて問ひし君はも",
      :description => "ヤマタノオロチを倒した",
      :priority => 3007,
    },
    3008 => {
      :icon_id => 191,
      :title => "月は無慈悲な夜の女王",
      :description => "玉藻を倒した",
      :priority => 3008,
    },
    3009 => {
      :icon_id => 191,
      :title => "ハインリヒの代わりに",
      :description => "黒のアリスを倒した",
      :priority => 3009,
    },
    3070 => {
      :icon_id => 191,
      :title => "未踏の英雄",
      :description => "混沌の迷宮に立ち入る事なくエンディングを迎えた",
      :priority => 3070,
    },
#    3081 => {
#      :icon_id => 193,
#      :title => "試練チャレンジャー",
#      :description => "混沌の試練レベル1をクリアした",
#      :priority => 3081,
#    },
#    3082 => {
#      :icon_id => 192,
#      :title => "試練エキスパート",
#      :description => "混沌の試練レベル2をクリアした",
#      :priority => 3082,
#    },
#    3083 => {
#      :icon_id => 192,
#      :title => "試練マスター",
#      :description => "混沌の試練レベル3をクリアした",
#      :priority => 3083,
#    },
#    3084 => {
#      :icon_id => 191,
#      :title => "試練ゴッド",
#      :description => "混沌の試練レベル4をクリアした",
#      :priority => 3084,
#    },
#    3085 => {
#      :icon_id => 191,
#      :title => "試練カオス",
#      :description => "混沌の試練レベル5をクリアした",
#      :priority => 3085,
#    },
    3100 => {
      :icon_id => 193,
      :title => "迷宮チャレンジャー",
      :description => "混沌の迷宮10階層に辿り着いた",
      :priority => 3100,
    },
    3101 => {
      :icon_id => 192,
      :title => "迷宮エキスパート",
      :description => "混沌の迷宮50階層に辿り着いた",
      :priority => 3101,
    },
    3102 => {
      :icon_id => 192,
      :title => "迷宮マスター",
      :description => "混沌の迷宮100階層に辿り着いた",
      :priority => 3102,
    },
    3103 => {
      :icon_id => 191,
      :title => "迷宮ゴッド",
      :description => "混沌の迷宮200階層に辿り着いた",
      :priority => 3103,
    },
    3104 => {
      :icon_id => 191,
      :title => "迷宮カオス",
      :description => "混沌の迷宮300階層に辿り着いた",
      :priority => 3104,
    },
    3110 => {
      :icon_id => 193,
      :title => "修羅ビギナー",
      :description => "混沌の迷宮・修羅20階層に辿り着いた",
      :priority => 3110,
    },
    3111 => {
      :icon_id => 192,
      :title => "真の修羅",
      :description => "混沌の迷宮・修羅50階層に辿り着いた",
      :priority => 3111,
    },
    3112 => {
      :icon_id => 191,
      :title => "修羅の中の修羅",
      :description => "混沌の迷宮・修羅100階層に辿り着いた",
      :priority => 3112,
    },
    4001=> {
      :icon_id => 193,
      :title => "死神もにっこり",
      :description => "死神チャレンジで百万ダメージを達成した",
      :priority => 4001,
    },
    4002=> {
      :icon_id => 192,
      :title => "死神もびっくり",
      :description => "死神チャレンジで一億ダメージを達成した",
      :priority => 4002,
    },
    4003=> {
      :icon_id => 191,
      :title => "死神の死神",
      :description => "死神チャレンジで一兆ダメージを達成した",
      :priority => 4003,
    },

  }
end

